{{- $labels := include "common.labels" . -}}
{{- range .Values.persistences }}
{{- if .configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- $labels | nindent 4 }}
data:
  {{ .subPath }}: |
    {{- .values | nindent 4 }}
{{- end }}
{{- end }}