{{- if .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "common.fullname" .) }}
  labels: {{- include "common.labels" $ | nindent 4 }}
type: Opaque
{{- with .Values.secret.values }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}