{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.monitoring.serviceMonitor.additionalServiceMonitorLabels }}
{{ toYaml .Values.monitoring.serviceMonitor.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}    
  name: {{ template "common.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  {{- if .Values.monitoring.serviceMonitor.endpoints }}
    {{ toYaml .Values.monitoring.serviceMonitor.endpoints | indent 4 }}
  {{- else }}
    - port: "{{ .Values.monitoring.serviceMonitor.port }}"
      interval: '{{ .Values.monitoring.serviceMonitor.interval | default "15s" }}'
      honorLabels: true
      scrapeTimeout: '{{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}'
      {{- if .Values.monitoring.serviceMonitor.params }}
      params:
        {{- range $key, $value := .Values.monitoring.serviceMonitor.params }}
        {{ $key }}: 
          - {{ $value | quote }}
        {{- end }}
      {{- end }}
      path: '{{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}'
      {{- if .Values.monitoring.serviceMonitor.additionalLabels }}
      {{- range $key, $value := .Values.monitoring.serviceMonitor.additionalLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
      
  {{- end }}
{{- end }}