apiVersion: v2
name: crunchy-postgres-cluster
description: Crunchy PostgresCluster consuming an existing OpenShift MCG/NooBaa ObjectBucketClaim for pgBackRest S3 backups
type: application
version: 1.0.0
appVersion: "16"
