---
{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "grafana-dex.fullname" . }}-oauth-sa-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "grafana-dex.fullname" . }}-oauth-sa
  labels:
  {{- include "grafana-dex.labels" . | nindent 4 }}
{{- end}}