---
{{- if .Values.dex.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
    {{- include "grafana-dex.labels" . | nindent 4 }}
  name: {{ include "grafana-dex.fullname" .}}-dex
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: {{ include "grafana-dex.fullname" .}}-oauth-sa
      containers:
      - image: ghcr.io/dexidp/dex:v2.32.0
        name: dex
        # command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        command:
          - /usr/local/bin/docker-entrypoint
          - dex
          - serve
          - /etc/dex/cfg/config.yaml
        ports:
        - name: http
          containerPort: 8080

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: custom-ca-bundle-store
          mountPath: /etc/ssl/certs/
        env:
        - name: OPENSHIFT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "grafana-dex.fullname" .}}-oauth-sa-secret
              key: token

        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 5556
        #     scheme: HTTP
      volumes:
      - name: config
        configMap:
          name: {{ include "grafana-dex.fullname" .}}-dex
          items:
          - key: config.yaml
            path: config.yaml
      - name: custom-ca-bundle-store
        secret:
          secretName: grafana-oauth-sa-secret
{{- end}}
