---
{{- $oauthEnabled := .Values.grafana.auth.generic_oauth.enabled | default false }}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ include "grafana-dex.fullname" . }}
  labels:
    app: grafana
  {{- include "grafana-dex.labels" . | nindent 4 }}
spec:
  # An empty route spec is enough to signal the creation of a default
  # route to the operator. This can also be used to override defaults
  # in the route spec.
  route:
    spec:
      host: {{ .Values.grafana.route.host }}
  config:
    log:
      mode: "console"
    server:
      domain: {{ .Values.grafana.route.host }}
      enforce_domain: 'false'
      root_url: https://%(domain)s/
    users:
      auto_assign_org: "True"
      default_theme: light
      editors_can_admin: "True"
      viewers_can_edit: "True"
{{- if not $oauthEnabled }}
    auth:
      disable_login_form: "false"
    security:
{{ .Values.grafana.security | toYaml | indent 6 }}
{{ else }}
    auth.generic_oauth:
      allow_assign_grafana_admin: 'true'
      allow_sign_up: 'true'
      api_url: >-
        {{ .Values.dex.dex_url }}/dex/userinfo
      auth_url: >-
        {{ .Values.dex.dex_url }}/dex/auth
      client_id: grafana
      email_attribute_path: email
      enabled: 'true'
      login_attribute_path: preferred_username
      name: openshift
      name_attribute_path: name
      role_attribute_path: >-
        contains(groups[*], '{{ .Values.dex.admin_role }}') && 'GrafanaAdmin' ||
        contains(groups[*], 'grafana-editor') && 'Editor' || 'Viewer'
      scopes: openid profile email groups
      # tls_skip_verify_insecure: true
      token_url: >-
        {{ .Values.dex.dex_url }}/dex/token
{{- end }}
  deployment:
    spec:
      template:
        spec:
          volumes:
            - name: trusted-ca
              configMap:
                name: {{ include "grafana-dex.fullname" . }}-certs
                items:
                  - key: ca-bundle.crt
                    path: ca-bundle.crt
          containers:
            - name: grafana
              volumeMounts:
                - name: trusted-ca
                  mountPath: /etc/ssl/certs/ca-certificates.crt
                  subPath: ca-bundle.crt
                  readOnly: true
              env:
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  value: grafanasecret